// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts && tsx prisma/seed-extra.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // directUrl is supported at runtime but not yet in the type definition
    ...({ directUrl: process.env["DATABASE_URL_DIRECT"] } as object),
  } as { url?: string },
});
